baseurl = "https://xjtu-netfun.github.io"
title = "NetFun"
theme = "blist"
languageCode = 'en-us'

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Net<b>Fun</b> Lab"
      introSubtitle = "@ ANTS (<b>A</b>dvanced <b>N</b>e<b>T</b>worked <b>S</b>ystem) Group in XJTU (<b>X</b>i'an <b>J</b>iao<b>t</b>ong <b>U</b>niversity)"
      news = "News"

    [[languages.en.params.about]]
      content = "We are a research lab of ANTS (Advanced NeTworked Systems) group, led by associate professor Hao Li."

    [[languages.en.params.about]]
      content = "Our lab focuses on the programmable networks."

    [[languages.en.params.about]]
      content = "Undergraduate students who are highly self-motivated, and interested in this research direction, are welcome to join our NetFun lab (contact: hao.li@xjtu.edu.cn)"

    # [[languages.en.menu.main]]
    #     name = "About"
    #     url = "about"
    #     weight = 1
    [[languages.en.menu.main]]
        name = "Research"
        url = "research"
        weight = 2

    [[languages.en.menu.main]]
        name = "People"
        url = "people"
        weight = 3

    [[languages.en.menu.main]]
        name = "Publications"
        url = "papers"
        weight = 4

    # [[languages.en.menu.main]]
    #     name = "Courses"
    #     url = "courses"
    #     weight = 4
    #
    #[[languages.en.menu.main]]
    #    name = "Join us"
    #    url = "joinus"
    #    weight = 5

  [languages.zh]
    contentDir = "content/zh"
    weight = 2
    languageName = "Chinese"
    [languages.zh.params]
      description = "可编程网络团队"
      introTitle = "<b>可编程网络团队</b>"
      introSubtitle = "西安交通大学网络系统组 @ ANTS (<b>A</b>dvanced <b>N</b>etwork <b>T</b>echnology & <b>S</b>ystem) Group in XJTU (<b>X</b>i'an <b>J</b>iao<b>t</b>ong <b>U</b>niversity)"

      news = "新闻"
      homepage.social.title = "联系我们团队"
      homepage.social.description = "如果你对我们 NetFun 团队感兴趣，欢迎联系我们！"

    [[languages.zh.params.about]]
      content = "我们是一个由李昊副教授领导的先进网络系统（ANTS）小组研究实验室。"
    [[languages.zh.params.about]]
      content = "我们的实验室专注于可编程网络。"
    [[languages.zh.params.about]]
      content = "欢迎自学能力强、对该研究方向感兴趣的本科生加入我们的 NetFun 实验室（联系人：hao.li@xjtu.edu.cn）。"

    # [[languages.zh.menu.main]]
    #     name = "实验室介绍"
    #     url = "about"
    #     weight = 1

    [[languages.zh.menu.main]]
        name = "研究领域"
        url = "research"
        weight = 2

    [[languages.zh.menu.main]]
        name = "团队成员"
        url = "people"
        weight = 3

    [[languages.zh.menu.main]]
        name = "论文发表"
        url = "papers"
        weight = 4

    #[[languages.zh.menu.main]]
    #    name = "Join us"
    #    url = "/joinus"
    #    weight = 5

    # [[languages.zh.menu.main]]
    #     name = "课程信息"
    #     url = "zh/courses"
    #     weight = 4

    # [[languages.zh.menu.main]]
    #     name = "博客"
    #     url = "blog"
    #     weight = 5

[[params.introImages]]
  src = "/intro/intro1.jpg"
[[params.introImages]]
  src = "/intro/intro2.jpg"
[[params.introImages]]
  src = "/intro/intro3.jpg"
[[params.introImages]]
  src = "/intro/intro4.jpg"
[[params.introImages]]
  src = "/intro/intro5.jpg"
[[params.introImages]]
  src = "/intro/group3.jpg"

# [[params.logo]]
#   src = "/logo-square-remake.png"
#   url = "/"
[[params.logo]]
  light = "/ants-logo.png"
  dark = "/ants-logo-dark.png"
  url = "http://ants.xjtu.edu.cn"
# [[params.logo]]
#   src = "/netfun.png"
#   url = "/"

[params]
  altLogo = "/ants-logo.png"
  altLogoDark = "/ants-logo-dark.png"
  teamLogo = "/netfun.png"
  teamLogoDark = "/netfun-dark.png"

  defaultContentLanguage = "en"
  defaultContentLanguageInSubdir = true

  enableEmoji = true
  enableRobotsTXT = true

  hasCJKLanguage = true

  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  # enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  # searchKeys = [
  #   "tags",
  #   "date",
  #   "categories",
  #   "summary",
  #   "content",
  #   "link",
  #   "author"
  # ]

  # Custom copyright - optional
  copyright = "Copyright © 2024 - NetFun Lab - ANTS Group in XJTU · All rights reserved"
  favicon = "/logo-square-remake.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "news"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true
  tocOpen = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

  joinus = true

[params.homepage.social]
  # Global params common for both languages
  title = "Contact Us"
  description = "If you are interested in our NetFun lab in ANTS group, feel free to contact."

  [[params.homepage.social.icons]]
    website = "email"
    url = "hao.li@xjtu.edu.cn"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/XJTU-NetFun"
  [[params.homepage.social.icons]]
    website = "logo"
    src = "/xjtu.png"
    url = "https://www.xjtu.edu.cn"

[build]
  writeStats = true
  future = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
